/* eslint-disable */
import * as types from './graphql';
import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "fragment CalendarEventFields on CalendarEvent {\n  id\n  title\n  startsAt\n  endsAt\n  isPromoted\n}\n\nquery CalendarEvents($from: DateTime!, $to: DateTime!) {\n  calendarEvents(from: $from, to: $to) {\n    ...CalendarEventFields\n  }\n}\n\nquery CalendarStatus {\n  calendarStatus {\n    connected\n    lastSyncedAt\n    autoPromote\n    defaultProjectId\n    googleLinked\n    needsReconnect\n  }\n}\n\nmutation SyncCalendar($from: DateTime!, $to: DateTime!) {\n  syncCalendar(from: $from, to: $to) {\n    stored\n    removed\n    autoPromoted\n    needsReconnect\n  }\n}\n\nmutation PromoteCalendarEvent($id: ID!, $projectId: ID) {\n  promoteCalendarEvent(id: $id, projectId: $projectId) {\n    ...TimeEntryFields\n  }\n}\n\nmutation DismissCalendarEvent($id: ID!) {\n  dismissCalendarEvent(id: $id)\n}\n\nmutation UpdateCalendarSettings($autoPromote: Boolean, $defaultProjectId: ID, $clearDefaultProject: Boolean) {\n  updateCalendarSettings(\n    autoPromote: $autoPromote\n    defaultProjectId: $defaultProjectId\n    clearDefaultProject: $clearDefaultProject\n  ) {\n    connected\n    lastSyncedAt\n    autoPromote\n    defaultProjectId\n    googleLinked\n    needsReconnect\n  }\n}": typeof types.CalendarEventFieldsFragmentDoc,
    "fragment PreferencesFields on Preferences {\n  weekStartsOn\n  showWeekend\n  dayStartHour\n  dayEndHour\n  calendarZoom\n  dailyTargetMinutes\n  weeklyTargetMinutes\n}\n\nquery Preferences {\n  preferences {\n    ...PreferencesFields\n  }\n}\n\nmutation UpdatePreferences($input: UpdatePreferencesInput!) {\n  updatePreferences(input: $input) {\n    ...PreferencesFields\n  }\n}": typeof types.PreferencesFieldsFragmentDoc,
    "fragment ProjectFields on Project {\n  id\n  name\n  color\n  defaultBillingType\n  polarisTask\n  archived\n  createdAt\n  client {\n    id\n    name\n    shortName\n  }\n}\n\nquery Projects {\n  projects {\n    ...ProjectFields\n  }\n}\n\nquery ProjectSummaries($includeArchived: Boolean) {\n  projectSummaries(includeArchived: $includeArchived) {\n    totalMinutes\n    entryCount\n    lastTrackedAt\n    project {\n      ...ProjectFields\n    }\n  }\n}\n\nquery Clients {\n  clients {\n    id\n    name\n    shortName\n    color\n    archived\n  }\n}\n\nmutation CreateProject($input: CreateProjectInput!) {\n  createProject(input: $input) {\n    ...ProjectFields\n  }\n}\n\nmutation UpdateProject($id: ID!, $input: UpdateProjectInput!) {\n  updateProject(id: $id, input: $input) {\n    ...ProjectFields\n  }\n}\n\nmutation DeleteProject($id: ID!) {\n  deleteProject(id: $id)\n}\n\nmutation CreateClient($input: CreateClientInput!) {\n  createClient(input: $input) {\n    id\n    name\n    shortName\n    color\n    archived\n  }\n}": typeof types.ProjectFieldsFragmentDoc,
    "fragment TicketSummaryFields on TicketSummary {\n  ticketNumber\n  trackedMinutes\n  entryCount\n  firstTrackedAt\n  lastTrackedAt\n  estimateMinMinutes\n  estimateMaxMinutes\n  estimateNotes\n  remainingMinutes\n  status\n  project {\n    ...ProjectFields\n  }\n}\n\nquery TicketSummaries {\n  ticketSummaries {\n    ...TicketSummaryFields\n  }\n}\n\nmutation SetTicketEstimate($input: SetTicketEstimateInput!) {\n  setTicketEstimate(input: $input) {\n    ...TicketSummaryFields\n  }\n}\n\nmutation ClearTicketEstimate($projectId: ID!, $ticketNumber: String!) {\n  clearTicketEstimate(projectId: $projectId, ticketNumber: $ticketNumber) {\n    ...TicketSummaryFields\n  }\n}\n\nmutation ImportTimeEntries($rows: [ImportTimeEntryInput!]!, $createMissingProjects: Boolean) {\n  importTimeEntries(rows: $rows, createMissingProjects: $createMissingProjects) {\n    imported\n    duplicatesSkipped\n    unmatchedRows\n    projectsCreated\n    clientsCreated\n  }\n}": typeof types.TicketSummaryFieldsFragmentDoc,
    "fragment TimeEntryFields on TimeEntry {\n  id\n  description\n  ticketNumber\n  billingType\n  kind\n  unbillablePercent\n  startedAt\n  endedAt\n  durationSeconds\n  elapsedSeconds\n  isRunning\n  timesheetDurationMinutes\n  billedMinutes\n  timesheetEnteredAt\n  nonBillableEnteredAt\n  billableMinutes\n  unbillableMinutes\n  project {\n    id\n    name\n    color\n    defaultBillingType\n    polarisTask\n    client {\n      id\n      name\n      shortName\n    }\n  }\n}\n\nquery Entries($from: DateTime!, $to: DateTime!) {\n  entries(from: $from, to: $to) {\n    ...TimeEntryFields\n  }\n}\n\nquery DescriptionSuggestions($query: String!, $limit: Int) {\n  descriptionSuggestions(query: $query, limit: $limit) {\n    ...TimeEntryFields\n  }\n}\n\nmutation CreateTimeEntry($input: CreateTimeEntryInput!) {\n  createTimeEntry(input: $input) {\n    ...TimeEntryFields\n  }\n}\n\nmutation UpdateTimeEntry($id: ID!, $input: UpdateTimeEntryInput!) {\n  updateTimeEntry(id: $id, input: $input) {\n    ...TimeEntryFields\n  }\n}\n\nmutation DeleteTimeEntry($id: ID!) {\n  deleteTimeEntry(id: $id)\n}": typeof types.TimeEntryFieldsFragmentDoc,
    "query TimesheetWeek($weekStart: Date!, $weekEnd: Date!) {\n  timesheetWeek(weekStart: $weekStart, weekEnd: $weekEnd) {\n    weekStart\n    weekEnd\n    targetMinutes\n    completedAt\n    isComplete\n  }\n}\n\nmutation MarkTimeEntriesTransferred($ids: [ID!]!, $transferred: Boolean!, $portion: EntryPortion) {\n  markTimeEntriesTransferred(\n    ids: $ids\n    transferred: $transferred\n    portion: $portion\n  ) {\n    ...TimeEntryFields\n  }\n}\n\nmutation CompleteTimesheetWeek($weekStart: Date!, $weekEnd: Date!) {\n  completeTimesheetWeek(weekStart: $weekStart, weekEnd: $weekEnd) {\n    weekStart\n    completedAt\n    isComplete\n  }\n}\n\nmutation ReopenTimesheetWeek($weekStart: Date!, $weekEnd: Date!) {\n  reopenTimesheetWeek(weekStart: $weekStart, weekEnd: $weekEnd) {\n    weekStart\n    completedAt\n    isComplete\n  }\n}": typeof types.TimesheetWeekDocument,
};
const documents: Documents = {
    "fragment CalendarEventFields on CalendarEvent {\n  id\n  title\n  startsAt\n  endsAt\n  isPromoted\n}\n\nquery CalendarEvents($from: DateTime!, $to: DateTime!) {\n  calendarEvents(from: $from, to: $to) {\n    ...CalendarEventFields\n  }\n}\n\nquery CalendarStatus {\n  calendarStatus {\n    connected\n    lastSyncedAt\n    autoPromote\n    defaultProjectId\n    googleLinked\n    needsReconnect\n  }\n}\n\nmutation SyncCalendar($from: DateTime!, $to: DateTime!) {\n  syncCalendar(from: $from, to: $to) {\n    stored\n    removed\n    autoPromoted\n    needsReconnect\n  }\n}\n\nmutation PromoteCalendarEvent($id: ID!, $projectId: ID) {\n  promoteCalendarEvent(id: $id, projectId: $projectId) {\n    ...TimeEntryFields\n  }\n}\n\nmutation DismissCalendarEvent($id: ID!) {\n  dismissCalendarEvent(id: $id)\n}\n\nmutation UpdateCalendarSettings($autoPromote: Boolean, $defaultProjectId: ID, $clearDefaultProject: Boolean) {\n  updateCalendarSettings(\n    autoPromote: $autoPromote\n    defaultProjectId: $defaultProjectId\n    clearDefaultProject: $clearDefaultProject\n  ) {\n    connected\n    lastSyncedAt\n    autoPromote\n    defaultProjectId\n    googleLinked\n    needsReconnect\n  }\n}": types.CalendarEventFieldsFragmentDoc,
    "fragment PreferencesFields on Preferences {\n  weekStartsOn\n  showWeekend\n  dayStartHour\n  dayEndHour\n  calendarZoom\n  dailyTargetMinutes\n  weeklyTargetMinutes\n}\n\nquery Preferences {\n  preferences {\n    ...PreferencesFields\n  }\n}\n\nmutation UpdatePreferences($input: UpdatePreferencesInput!) {\n  updatePreferences(input: $input) {\n    ...PreferencesFields\n  }\n}": types.PreferencesFieldsFragmentDoc,
    "fragment ProjectFields on Project {\n  id\n  name\n  color\n  defaultBillingType\n  polarisTask\n  archived\n  createdAt\n  client {\n    id\n    name\n    shortName\n  }\n}\n\nquery Projects {\n  projects {\n    ...ProjectFields\n  }\n}\n\nquery ProjectSummaries($includeArchived: Boolean) {\n  projectSummaries(includeArchived: $includeArchived) {\n    totalMinutes\n    entryCount\n    lastTrackedAt\n    project {\n      ...ProjectFields\n    }\n  }\n}\n\nquery Clients {\n  clients {\n    id\n    name\n    shortName\n    color\n    archived\n  }\n}\n\nmutation CreateProject($input: CreateProjectInput!) {\n  createProject(input: $input) {\n    ...ProjectFields\n  }\n}\n\nmutation UpdateProject($id: ID!, $input: UpdateProjectInput!) {\n  updateProject(id: $id, input: $input) {\n    ...ProjectFields\n  }\n}\n\nmutation DeleteProject($id: ID!) {\n  deleteProject(id: $id)\n}\n\nmutation CreateClient($input: CreateClientInput!) {\n  createClient(input: $input) {\n    id\n    name\n    shortName\n    color\n    archived\n  }\n}": types.ProjectFieldsFragmentDoc,
    "fragment TicketSummaryFields on TicketSummary {\n  ticketNumber\n  trackedMinutes\n  entryCount\n  firstTrackedAt\n  lastTrackedAt\n  estimateMinMinutes\n  estimateMaxMinutes\n  estimateNotes\n  remainingMinutes\n  status\n  project {\n    ...ProjectFields\n  }\n}\n\nquery TicketSummaries {\n  ticketSummaries {\n    ...TicketSummaryFields\n  }\n}\n\nmutation SetTicketEstimate($input: SetTicketEstimateInput!) {\n  setTicketEstimate(input: $input) {\n    ...TicketSummaryFields\n  }\n}\n\nmutation ClearTicketEstimate($projectId: ID!, $ticketNumber: String!) {\n  clearTicketEstimate(projectId: $projectId, ticketNumber: $ticketNumber) {\n    ...TicketSummaryFields\n  }\n}\n\nmutation ImportTimeEntries($rows: [ImportTimeEntryInput!]!, $createMissingProjects: Boolean) {\n  importTimeEntries(rows: $rows, createMissingProjects: $createMissingProjects) {\n    imported\n    duplicatesSkipped\n    unmatchedRows\n    projectsCreated\n    clientsCreated\n  }\n}": types.TicketSummaryFieldsFragmentDoc,
    "fragment TimeEntryFields on TimeEntry {\n  id\n  description\n  ticketNumber\n  billingType\n  kind\n  unbillablePercent\n  startedAt\n  endedAt\n  durationSeconds\n  elapsedSeconds\n  isRunning\n  timesheetDurationMinutes\n  billedMinutes\n  timesheetEnteredAt\n  nonBillableEnteredAt\n  billableMinutes\n  unbillableMinutes\n  project {\n    id\n    name\n    color\n    defaultBillingType\n    polarisTask\n    client {\n      id\n      name\n      shortName\n    }\n  }\n}\n\nquery Entries($from: DateTime!, $to: DateTime!) {\n  entries(from: $from, to: $to) {\n    ...TimeEntryFields\n  }\n}\n\nquery DescriptionSuggestions($query: String!, $limit: Int) {\n  descriptionSuggestions(query: $query, limit: $limit) {\n    ...TimeEntryFields\n  }\n}\n\nmutation CreateTimeEntry($input: CreateTimeEntryInput!) {\n  createTimeEntry(input: $input) {\n    ...TimeEntryFields\n  }\n}\n\nmutation UpdateTimeEntry($id: ID!, $input: UpdateTimeEntryInput!) {\n  updateTimeEntry(id: $id, input: $input) {\n    ...TimeEntryFields\n  }\n}\n\nmutation DeleteTimeEntry($id: ID!) {\n  deleteTimeEntry(id: $id)\n}": types.TimeEntryFieldsFragmentDoc,
    "query TimesheetWeek($weekStart: Date!, $weekEnd: Date!) {\n  timesheetWeek(weekStart: $weekStart, weekEnd: $weekEnd) {\n    weekStart\n    weekEnd\n    targetMinutes\n    completedAt\n    isComplete\n  }\n}\n\nmutation MarkTimeEntriesTransferred($ids: [ID!]!, $transferred: Boolean!, $portion: EntryPortion) {\n  markTimeEntriesTransferred(\n    ids: $ids\n    transferred: $transferred\n    portion: $portion\n  ) {\n    ...TimeEntryFields\n  }\n}\n\nmutation CompleteTimesheetWeek($weekStart: Date!, $weekEnd: Date!) {\n  completeTimesheetWeek(weekStart: $weekStart, weekEnd: $weekEnd) {\n    weekStart\n    completedAt\n    isComplete\n  }\n}\n\nmutation ReopenTimesheetWeek($weekStart: Date!, $weekEnd: Date!) {\n  reopenTimesheetWeek(weekStart: $weekStart, weekEnd: $weekEnd) {\n    weekStart\n    completedAt\n    isComplete\n  }\n}": types.TimesheetWeekDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment CalendarEventFields on CalendarEvent {\n  id\n  title\n  startsAt\n  endsAt\n  isPromoted\n}\n\nquery CalendarEvents($from: DateTime!, $to: DateTime!) {\n  calendarEvents(from: $from, to: $to) {\n    ...CalendarEventFields\n  }\n}\n\nquery CalendarStatus {\n  calendarStatus {\n    connected\n    lastSyncedAt\n    autoPromote\n    defaultProjectId\n    googleLinked\n    needsReconnect\n  }\n}\n\nmutation SyncCalendar($from: DateTime!, $to: DateTime!) {\n  syncCalendar(from: $from, to: $to) {\n    stored\n    removed\n    autoPromoted\n    needsReconnect\n  }\n}\n\nmutation PromoteCalendarEvent($id: ID!, $projectId: ID) {\n  promoteCalendarEvent(id: $id, projectId: $projectId) {\n    ...TimeEntryFields\n  }\n}\n\nmutation DismissCalendarEvent($id: ID!) {\n  dismissCalendarEvent(id: $id)\n}\n\nmutation UpdateCalendarSettings($autoPromote: Boolean, $defaultProjectId: ID, $clearDefaultProject: Boolean) {\n  updateCalendarSettings(\n    autoPromote: $autoPromote\n    defaultProjectId: $defaultProjectId\n    clearDefaultProject: $clearDefaultProject\n  ) {\n    connected\n    lastSyncedAt\n    autoPromote\n    defaultProjectId\n    googleLinked\n    needsReconnect\n  }\n}"): (typeof documents)["fragment CalendarEventFields on CalendarEvent {\n  id\n  title\n  startsAt\n  endsAt\n  isPromoted\n}\n\nquery CalendarEvents($from: DateTime!, $to: DateTime!) {\n  calendarEvents(from: $from, to: $to) {\n    ...CalendarEventFields\n  }\n}\n\nquery CalendarStatus {\n  calendarStatus {\n    connected\n    lastSyncedAt\n    autoPromote\n    defaultProjectId\n    googleLinked\n    needsReconnect\n  }\n}\n\nmutation SyncCalendar($from: DateTime!, $to: DateTime!) {\n  syncCalendar(from: $from, to: $to) {\n    stored\n    removed\n    autoPromoted\n    needsReconnect\n  }\n}\n\nmutation PromoteCalendarEvent($id: ID!, $projectId: ID) {\n  promoteCalendarEvent(id: $id, projectId: $projectId) {\n    ...TimeEntryFields\n  }\n}\n\nmutation DismissCalendarEvent($id: ID!) {\n  dismissCalendarEvent(id: $id)\n}\n\nmutation UpdateCalendarSettings($autoPromote: Boolean, $defaultProjectId: ID, $clearDefaultProject: Boolean) {\n  updateCalendarSettings(\n    autoPromote: $autoPromote\n    defaultProjectId: $defaultProjectId\n    clearDefaultProject: $clearDefaultProject\n  ) {\n    connected\n    lastSyncedAt\n    autoPromote\n    defaultProjectId\n    googleLinked\n    needsReconnect\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment PreferencesFields on Preferences {\n  weekStartsOn\n  showWeekend\n  dayStartHour\n  dayEndHour\n  calendarZoom\n  dailyTargetMinutes\n  weeklyTargetMinutes\n}\n\nquery Preferences {\n  preferences {\n    ...PreferencesFields\n  }\n}\n\nmutation UpdatePreferences($input: UpdatePreferencesInput!) {\n  updatePreferences(input: $input) {\n    ...PreferencesFields\n  }\n}"): (typeof documents)["fragment PreferencesFields on Preferences {\n  weekStartsOn\n  showWeekend\n  dayStartHour\n  dayEndHour\n  calendarZoom\n  dailyTargetMinutes\n  weeklyTargetMinutes\n}\n\nquery Preferences {\n  preferences {\n    ...PreferencesFields\n  }\n}\n\nmutation UpdatePreferences($input: UpdatePreferencesInput!) {\n  updatePreferences(input: $input) {\n    ...PreferencesFields\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment ProjectFields on Project {\n  id\n  name\n  color\n  defaultBillingType\n  polarisTask\n  archived\n  createdAt\n  client {\n    id\n    name\n    shortName\n  }\n}\n\nquery Projects {\n  projects {\n    ...ProjectFields\n  }\n}\n\nquery ProjectSummaries($includeArchived: Boolean) {\n  projectSummaries(includeArchived: $includeArchived) {\n    totalMinutes\n    entryCount\n    lastTrackedAt\n    project {\n      ...ProjectFields\n    }\n  }\n}\n\nquery Clients {\n  clients {\n    id\n    name\n    shortName\n    color\n    archived\n  }\n}\n\nmutation CreateProject($input: CreateProjectInput!) {\n  createProject(input: $input) {\n    ...ProjectFields\n  }\n}\n\nmutation UpdateProject($id: ID!, $input: UpdateProjectInput!) {\n  updateProject(id: $id, input: $input) {\n    ...ProjectFields\n  }\n}\n\nmutation DeleteProject($id: ID!) {\n  deleteProject(id: $id)\n}\n\nmutation CreateClient($input: CreateClientInput!) {\n  createClient(input: $input) {\n    id\n    name\n    shortName\n    color\n    archived\n  }\n}"): (typeof documents)["fragment ProjectFields on Project {\n  id\n  name\n  color\n  defaultBillingType\n  polarisTask\n  archived\n  createdAt\n  client {\n    id\n    name\n    shortName\n  }\n}\n\nquery Projects {\n  projects {\n    ...ProjectFields\n  }\n}\n\nquery ProjectSummaries($includeArchived: Boolean) {\n  projectSummaries(includeArchived: $includeArchived) {\n    totalMinutes\n    entryCount\n    lastTrackedAt\n    project {\n      ...ProjectFields\n    }\n  }\n}\n\nquery Clients {\n  clients {\n    id\n    name\n    shortName\n    color\n    archived\n  }\n}\n\nmutation CreateProject($input: CreateProjectInput!) {\n  createProject(input: $input) {\n    ...ProjectFields\n  }\n}\n\nmutation UpdateProject($id: ID!, $input: UpdateProjectInput!) {\n  updateProject(id: $id, input: $input) {\n    ...ProjectFields\n  }\n}\n\nmutation DeleteProject($id: ID!) {\n  deleteProject(id: $id)\n}\n\nmutation CreateClient($input: CreateClientInput!) {\n  createClient(input: $input) {\n    id\n    name\n    shortName\n    color\n    archived\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment TicketSummaryFields on TicketSummary {\n  ticketNumber\n  trackedMinutes\n  entryCount\n  firstTrackedAt\n  lastTrackedAt\n  estimateMinMinutes\n  estimateMaxMinutes\n  estimateNotes\n  remainingMinutes\n  status\n  project {\n    ...ProjectFields\n  }\n}\n\nquery TicketSummaries {\n  ticketSummaries {\n    ...TicketSummaryFields\n  }\n}\n\nmutation SetTicketEstimate($input: SetTicketEstimateInput!) {\n  setTicketEstimate(input: $input) {\n    ...TicketSummaryFields\n  }\n}\n\nmutation ClearTicketEstimate($projectId: ID!, $ticketNumber: String!) {\n  clearTicketEstimate(projectId: $projectId, ticketNumber: $ticketNumber) {\n    ...TicketSummaryFields\n  }\n}\n\nmutation ImportTimeEntries($rows: [ImportTimeEntryInput!]!, $createMissingProjects: Boolean) {\n  importTimeEntries(rows: $rows, createMissingProjects: $createMissingProjects) {\n    imported\n    duplicatesSkipped\n    unmatchedRows\n    projectsCreated\n    clientsCreated\n  }\n}"): (typeof documents)["fragment TicketSummaryFields on TicketSummary {\n  ticketNumber\n  trackedMinutes\n  entryCount\n  firstTrackedAt\n  lastTrackedAt\n  estimateMinMinutes\n  estimateMaxMinutes\n  estimateNotes\n  remainingMinutes\n  status\n  project {\n    ...ProjectFields\n  }\n}\n\nquery TicketSummaries {\n  ticketSummaries {\n    ...TicketSummaryFields\n  }\n}\n\nmutation SetTicketEstimate($input: SetTicketEstimateInput!) {\n  setTicketEstimate(input: $input) {\n    ...TicketSummaryFields\n  }\n}\n\nmutation ClearTicketEstimate($projectId: ID!, $ticketNumber: String!) {\n  clearTicketEstimate(projectId: $projectId, ticketNumber: $ticketNumber) {\n    ...TicketSummaryFields\n  }\n}\n\nmutation ImportTimeEntries($rows: [ImportTimeEntryInput!]!, $createMissingProjects: Boolean) {\n  importTimeEntries(rows: $rows, createMissingProjects: $createMissingProjects) {\n    imported\n    duplicatesSkipped\n    unmatchedRows\n    projectsCreated\n    clientsCreated\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment TimeEntryFields on TimeEntry {\n  id\n  description\n  ticketNumber\n  billingType\n  kind\n  unbillablePercent\n  startedAt\n  endedAt\n  durationSeconds\n  elapsedSeconds\n  isRunning\n  timesheetDurationMinutes\n  billedMinutes\n  timesheetEnteredAt\n  nonBillableEnteredAt\n  billableMinutes\n  unbillableMinutes\n  project {\n    id\n    name\n    color\n    defaultBillingType\n    polarisTask\n    client {\n      id\n      name\n      shortName\n    }\n  }\n}\n\nquery Entries($from: DateTime!, $to: DateTime!) {\n  entries(from: $from, to: $to) {\n    ...TimeEntryFields\n  }\n}\n\nquery DescriptionSuggestions($query: String!, $limit: Int) {\n  descriptionSuggestions(query: $query, limit: $limit) {\n    ...TimeEntryFields\n  }\n}\n\nmutation CreateTimeEntry($input: CreateTimeEntryInput!) {\n  createTimeEntry(input: $input) {\n    ...TimeEntryFields\n  }\n}\n\nmutation UpdateTimeEntry($id: ID!, $input: UpdateTimeEntryInput!) {\n  updateTimeEntry(id: $id, input: $input) {\n    ...TimeEntryFields\n  }\n}\n\nmutation DeleteTimeEntry($id: ID!) {\n  deleteTimeEntry(id: $id)\n}"): (typeof documents)["fragment TimeEntryFields on TimeEntry {\n  id\n  description\n  ticketNumber\n  billingType\n  kind\n  unbillablePercent\n  startedAt\n  endedAt\n  durationSeconds\n  elapsedSeconds\n  isRunning\n  timesheetDurationMinutes\n  billedMinutes\n  timesheetEnteredAt\n  nonBillableEnteredAt\n  billableMinutes\n  unbillableMinutes\n  project {\n    id\n    name\n    color\n    defaultBillingType\n    polarisTask\n    client {\n      id\n      name\n      shortName\n    }\n  }\n}\n\nquery Entries($from: DateTime!, $to: DateTime!) {\n  entries(from: $from, to: $to) {\n    ...TimeEntryFields\n  }\n}\n\nquery DescriptionSuggestions($query: String!, $limit: Int) {\n  descriptionSuggestions(query: $query, limit: $limit) {\n    ...TimeEntryFields\n  }\n}\n\nmutation CreateTimeEntry($input: CreateTimeEntryInput!) {\n  createTimeEntry(input: $input) {\n    ...TimeEntryFields\n  }\n}\n\nmutation UpdateTimeEntry($id: ID!, $input: UpdateTimeEntryInput!) {\n  updateTimeEntry(id: $id, input: $input) {\n    ...TimeEntryFields\n  }\n}\n\nmutation DeleteTimeEntry($id: ID!) {\n  deleteTimeEntry(id: $id)\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query TimesheetWeek($weekStart: Date!, $weekEnd: Date!) {\n  timesheetWeek(weekStart: $weekStart, weekEnd: $weekEnd) {\n    weekStart\n    weekEnd\n    targetMinutes\n    completedAt\n    isComplete\n  }\n}\n\nmutation MarkTimeEntriesTransferred($ids: [ID!]!, $transferred: Boolean!, $portion: EntryPortion) {\n  markTimeEntriesTransferred(\n    ids: $ids\n    transferred: $transferred\n    portion: $portion\n  ) {\n    ...TimeEntryFields\n  }\n}\n\nmutation CompleteTimesheetWeek($weekStart: Date!, $weekEnd: Date!) {\n  completeTimesheetWeek(weekStart: $weekStart, weekEnd: $weekEnd) {\n    weekStart\n    completedAt\n    isComplete\n  }\n}\n\nmutation ReopenTimesheetWeek($weekStart: Date!, $weekEnd: Date!) {\n  reopenTimesheetWeek(weekStart: $weekStart, weekEnd: $weekEnd) {\n    weekStart\n    completedAt\n    isComplete\n  }\n}"): (typeof documents)["query TimesheetWeek($weekStart: Date!, $weekEnd: Date!) {\n  timesheetWeek(weekStart: $weekStart, weekEnd: $weekEnd) {\n    weekStart\n    weekEnd\n    targetMinutes\n    completedAt\n    isComplete\n  }\n}\n\nmutation MarkTimeEntriesTransferred($ids: [ID!]!, $transferred: Boolean!, $portion: EntryPortion) {\n  markTimeEntriesTransferred(\n    ids: $ids\n    transferred: $transferred\n    portion: $portion\n  ) {\n    ...TimeEntryFields\n  }\n}\n\nmutation CompleteTimesheetWeek($weekStart: Date!, $weekEnd: Date!) {\n  completeTimesheetWeek(weekStart: $weekStart, weekEnd: $weekEnd) {\n    weekStart\n    completedAt\n    isComplete\n  }\n}\n\nmutation ReopenTimesheetWeek($weekStart: Date!, $weekEnd: Date!) {\n  reopenTimesheetWeek(weekStart: $weekStart, weekEnd: $weekEnd) {\n    weekStart\n    completedAt\n    isComplete\n  }\n}"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;