fragment TimeEntryFields on TimeEntry {
    id
    description
    ticketNumber
    billingType
    kind
    unbillablePercent
    startedAt
    endedAt
    durationSeconds
    elapsedSeconds
    isRunning
    timesheetDurationMinutes
    billedMinutes
    timesheetEnteredAt
    nonBillableEnteredAt
    billableMinutes
    unbillableMinutes

    project {
        id
        name
        color
        defaultBillingType
        polarisTask

        client {
            id
            name
            shortName
        }
    }
}

query Entries($from: DateTime!, $to: DateTime!) {
    entries(from: $from, to: $to) {
        ...TimeEntryFields
    }
}

query DescriptionSuggestions($query: String!, $limit: Int) {
    descriptionSuggestions(query: $query, limit: $limit) {
        ...TimeEntryFields
    }
}

mutation CreateTimeEntry($input: CreateTimeEntryInput!) {
    createTimeEntry(input: $input) {
        ...TimeEntryFields
    }
}

mutation UpdateTimeEntry($id: ID!, $input: UpdateTimeEntryInput!) {
    updateTimeEntry(id: $id, input: $input) {
        ...TimeEntryFields
    }
}

mutation DeleteTimeEntry($id: ID!) {
    deleteTimeEntry(id: $id)
}
